CREATE TABLE autores (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(255),
    version integer
);

CREATE TABLE libros_autores (
    libro_isbn varchar(255) NOT NULL,
    autor_id integer NOT NULL,
    PRIMARY KEY (libro_isbn, autor_id)
);

CREATE TABLE libros (
    isbn varchar(255) PRIMARY KEY,
    titulo varchar(128),
    precio numeric(12,2),
    version integer
);

CREATE TABLE inventario (
    isbn varchar(255) PRIMARY KEY,
    vendidos integer,
    suministrados integer
);

CREATE TABLE clientes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(64),
    correo varchar(64),
    version integer
);

CREATE TABLE detalles_pedido (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id integer,
    cantidad integer,
    isbn varchar(64)
);

CREATE TABLE pedidos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id integer,
    total integer,
    estado smallint,
    fecha_realizado timestamp without time zone,
    fecha_entregado timestamp without time zone
);

-- Foreign Keys

ALTER TABLE libros_autores
    ADD CONSTRAINT fk_libros_autores_autores FOREIGN KEY (autor_id) REFERENCES autores(id),
    ADD CONSTRAINT fk_libros_autores_libros FOREIGN KEY (libro_isbn) REFERENCES libros(isbn);

ALTER TABLE inventario
    ADD CONSTRAINT fk_inventario_isbn
    FOREIGN KEY (isbn) REFERENCES libros(isbn);

ALTER TABLE detalles_pedido
    ADD CONSTRAINT fk_detalles_pedido_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
    ADD CONSTRAINT fk_detalles_pedido_libro FOREIGN KEY (isbn) REFERENCES libros(isbn);

ALTER TABLE pedidos
    ADD CONSTRAINT fk_pedidos_cliente
    FOREIGN KEY (cliente_id) REFERENCES clientes(id);
