CREATE TABLE autores (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(255),
    version integer
);

CREATE TABLE autores_libros (
    libro_isbn varchar(255) NOT NULL,
    autor_id integer NOT NULL,
    PRIMARY KEY (libro_isbn, autor_id)
);

CREATE TABLE libros (
    isbn varchar(255) PRIMARY KEY,
    titulo varchar(128),
    precio numeric(12,2),
    version integer
);

CREATE TABLE inventarios (
    libro_isbn varchar(255) PRIMARY KEY,
    vendidos integer,
    suministrados integer,
    version integer
);

CREATE TABLE clientes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre varchar(64),
    correo varchar(64),
    version integer
);

CREATE TABLE detalles_pedidos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id integer,
    libro_isbn varchar(64),
    cantidad integer,
    precio_unitario numeric(12,2)
);

CREATE TABLE pedidos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id integer,
    total integer,
    estado smallint,
    fecha_realizado timestamp without time zone,
    fecha_entregado timestamp without time zone
);

-- Foreign Keys

ALTER TABLE autores_libros
    ADD CONSTRAINT fk_autores_libros_autores FOREIGN KEY (autor_id) REFERENCES autores(id),
    ADD CONSTRAINT fk_autores_libros_libros FOREIGN KEY (libro_isbn) REFERENCES libros(isbn);

ALTER TABLE inventarios
    ADD CONSTRAINT fk_inventarios_libro_isbn
    FOREIGN KEY (libro_isbn) REFERENCES libros(isbn);

ALTER TABLE detalles_pedidos
    ADD CONSTRAINT fk_detalles_pedidos_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
    ADD CONSTRAINT fk_detalles_pedidos_libro FOREIGN KEY (libro_isbn) REFERENCES libros(isbn);

ALTER TABLE pedidos
    ADD CONSTRAINT fk_pedidos_cliente
    FOREIGN KEY (cliente_id) REFERENCES clientes(id);
