CREATE TABLE public.autores (
    id serial NOT NULL,
    nombre varchar(255),
    version integer
)
WITH (oids = false);

ALTER TABLE ONLY public.autores ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.autores ALTER COLUMN nombre SET STATISTICS 0;
ALTER TABLE ONLY public.autores ALTER COLUMN version SET STATISTICS 0;

CREATE TABLE public.libros_autores (
    libro_isbn varchar(255) NOT NULL,
    autor_id integer NOT NULL
)
WITH (oids = false);

ALTER TABLE ONLY public.libros_autores ALTER COLUMN libro_isbn SET STATISTICS 0;
ALTER TABLE ONLY public.libros_autores ALTER COLUMN autor_id SET STATISTICS 0;

CREATE TABLE public.libros (
    isbn varchar(255) NOT NULL,
    titulo varchar(128),
    precio numeric(12,2),
    version integer
)
WITH (oids = false);

ALTER TABLE ONLY public.libros ALTER COLUMN isbn SET STATISTICS 0;
ALTER TABLE ONLY public.libros ALTER COLUMN titulo SET STATISTICS 0;
ALTER TABLE ONLY public.libros ALTER COLUMN precio SET STATISTICS 0;
ALTER TABLE ONLY public.libros ALTER COLUMN version SET STATISTICS 0;

CREATE TABLE public.inventario (
    isbn varchar(255) NOT NULL,
    vendidos integer,
    suministrados integer
)
WITH (oids = false);

ALTER TABLE ONLY public.inventario ALTER COLUMN isbn SET STATISTICS 0;
ALTER TABLE ONLY public.inventario ALTER COLUMN vendidos SET STATISTICS 0;
ALTER TABLE ONLY public.inventario ALTER COLUMN suministrados SET STATISTICS 0;

CREATE TABLE public.clientes (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre varchar(64),
    correo varchar(64),
    version integer
)
WITH (oids = false);

ALTER TABLE ONLY public.clientes ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.clientes ALTER COLUMN nombre SET STATISTICS 0;
ALTER TABLE ONLY public.clientes ALTER COLUMN correo SET STATISTICS 0;
ALTER TABLE ONLY public.clientes ALTER COLUMN version SET STATISTICS 0;

CREATE TABLE public.detalles_pedido (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pedido_id integer,
    cantidad integer,
    isbn varchar(64)
)
WITH (oids = false);

ALTER TABLE ONLY public.detalles_pedido ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.detalles_pedido ALTER COLUMN pedido_id SET STATISTICS 0;
ALTER TABLE ONLY public.detalles_pedido ALTER COLUMN cantidad SET STATISTICS 0;
ALTER TABLE ONLY public.detalles_pedido ALTER COLUMN isbn SET STATISTICS 0;

CREATE TABLE public.pedidos (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_id integer,
    total integer,
    estado smallint,
    fecha_realizado timestamp without time zone,
    fecha_entregado timestamp without time zone
)
WITH (oids = false);

ALTER TABLE ONLY public.pedidos ALTER COLUMN id SET STATISTICS 0;
ALTER TABLE ONLY public.pedidos ALTER COLUMN cliente_id SET STATISTICS 0;
ALTER TABLE ONLY public.pedidos ALTER COLUMN total SET STATISTICS 0;
ALTER TABLE ONLY public.pedidos ALTER COLUMN estado SET STATISTICS 0;
ALTER TABLE ONLY public.pedidos ALTER COLUMN fecha_realizado SET STATISTICS 0;
ALTER TABLE ONLY public.pedidos ALTER COLUMN fecha_entregado SET STATISTICS 0;

-- Claves primarias y foráneas

ALTER TABLE ONLY public.autores
    ADD CONSTRAINT pk_autores
    PRIMARY KEY (id);

ALTER TABLE ONLY public.libros_autores
    ADD CONSTRAINT pk_libros_autores
    PRIMARY KEY (libro_isbn, autor_id);

ALTER TABLE ONLY public.libros_autores
    ADD CONSTRAINT fk_libros_autores_autores
    FOREIGN KEY (autor_id) REFERENCES autores(id);

ALTER TABLE ONLY public.libros
    ADD CONSTRAINT pk_libros
    PRIMARY KEY (isbn);

ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT pk_inventario
    PRIMARY KEY (isbn);

ALTER TABLE ONLY public.inventario
    ADD CONSTRAINT fk_inventario_isbn
    FOREIGN KEY (isbn) REFERENCES libros(isbn);

ALTER TABLE ONLY public.libros_autores
    ADD CONSTRAINT fk_libros_autores_libros
    FOREIGN KEY (libro_isbn) REFERENCES libros(isbn);

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT pk_clientes
    PRIMARY KEY (id);

ALTER TABLE ONLY public.detalles_pedido
    ADD CONSTRAINT pk_detalles_pedido
    PRIMARY KEY (id);

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pk_pedidos
    PRIMARY KEY (id);

ALTER TABLE ONLY public.detalles_pedido
    ADD CONSTRAINT fk_detalles_pedido_pedido
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id);

ALTER TABLE ONLY public.detalles_pedido
    ADD CONSTRAINT fk_detalles_pedido_libro
    FOREIGN KEY (isbn) REFERENCES libros(isbn);

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fk_pedidos_cliente
    FOREIGN KEY (cliente_id) REFERENCES clientes(id);

COMMENT ON SCHEMA public IS 'esquema público estándar';