apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-autores
  labels:
    app: app-autores
spec:
  replicas: 1
  selector:
    matchLabels:
     app: app-autores
  template:
    metadata:
      labels:
        app: app-autores
    spec:
      containers:
        - name: app-autores
          image: jcestrella/app-autores:v1.2.1
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              value: postgres
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: labcom,2015
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://base-de-datos:5432/db_libreria
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: CONSUL_HOST
              value: consul
            - name: CONSUL_PORT
              value: "8500"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: app-autores-service  # Nombre para la red interna
spec:
  type: NodePort             # Permite acceso externo rápido en Minikube
  selector:
    app: app-autores         # Conecta con tu pod
  ports:
    - protocol: TCP
      port: 8080             # Puerto en el Service
      targetPort: 8080       # Puerto de tu Quarkus
      nodePort: 30001        # (Opcional) Puerto fijo para probar fácil