apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-autores
  labels:
    app: app-autores
spec:
  replicas: 1
  selector:
    matchLabels:
     app: app-autores
  template:
    metadata:
      labels:
        app: app-autores
    spec:
      containers:
        - name: app-autores
          image: jcestrella/app-autores:v_ip_real
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              value: postgres
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: labcom,2015
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://base_de_datos:5432/db_libreria
            - name: QUARKUS_HTTP_PORT
              value: "8080"
            - name: CONSUL_HOST
              value: consul
            - name: CONSUL_PORT
              value: "8500"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
          # command:
          # - sh
          # - -c
          # - |
          #   apk add --no-cache curl bash &&
          #   curl -o /usr/local/bin/wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
          #   chmod +x /usr/local/bin/wait-for-it &&
          #   /usr/local/bin/wait-for-it base_de_datos:5432 -- java -jar /app/app.jar