apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-de-datos
  labels:
    app: base-de-datos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-de-datos
  template:
    metadata:
      labels:
        app: base-de-datos
    spec:
      containers:
        - name: base-de-datos
          image: postgres:17.5-alpine3.22
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "labcom,2015"
            - name: POSTGRES_DB
              value: db_libreria
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: base-de-datos
spec:
  selector:
    app: base-de-datos
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
