apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricas-base-datos
  labels:
    app: metricas-base-datos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricas-base-datos
  template:
    metadata:
      labels:
        app: metricas-base-datos
    spec:
      containers:
        - name: metricas-base-datos
          image: prometheuscommunity/postgres-exporter
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:labcom%2C2015@base-de-datos:5432/db_libreria?sslmode=disable"
          ports:
            - containerPort: 9187
---
apiVersion: v1
kind: Service
metadata:
  name: metricas-base-datos
spec:
  selector:
    app: metricas-base-datos
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
