
# Obtener libro por ISBN
GET http://localhost:9090/libros/100
Accept: application/json

###
# Obtener todos los libros
GET http://localhost:9090/libros
Accept: application/json

###
# Crear un libro
POST http://localhost:9090/libros
Content-Type: application/json
Accept: application/json

{
  "isbn": "104",
  "precio": 9.50,
  "titulo": "Infinix"
}

###
# Actualizar un libro
PUT http://localhost:9090/libros/1234567890
Content-Type: application/json
Accept: application/json

{
  "isbn": "1234567890",
  "precio": 1.50,
  "titulo": "Libro Actualizado"
}

###
# Eliminar un libro
DELETE http://localhost:9090/libros/1234567890
Accept: application/json
